"use client";

import React, { useState } from "react";
import { motion } from "framer-motion";
import { Download, Save, Star, ChevronRight, Stethoscope, FileText, CheckCircle2 } from "lucide-react";
import { cn } from "@/utils/cn";

export default function PostCallSummary({ durationSeconds }: { durationSeconds: number }) {
  const [rating, setRating] = useState(0);
  const [hoverRating, setHoverRating] = useState(0);
  const [review, setReview] = useState("");
  const [saved, setSaved] = useState(false);

  const m = Math.floor(durationSeconds / 60);
  const s = durationSeconds % 60;
  const durationText = `${m}m ${s}s`;

  return (
    <div className="min-h-screen w-full bg-[#060F1E] flex flex-col items-center py-16 px-4 overflow-y-auto">
      
      {/* Success Animation Header */}
      <div className="flex flex-col items-center mb-10 text-center">
         <div className="w-24 h-24 rounded-full bg-[#00C896]/10 flex items-center justify-center mb-6 relative">
            <div className="absolute inset-0 rounded-full border-2 border-[#00C896]/20 animate-ping" />
            <svg viewBox="0 0 52 52" className="w-12 h-12 text-[#00C896] stroke-current" strokeWidth="3" fill="none">
               <motion.path 
                 d="M14.1 27.2l7.1 7.2 16.7-16.8" 
                 strokeLinecap="round" 
                 strokeLinejoin="round" 
                 initial={{ strokeDasharray: 48, strokeDashoffset: 48 }}
                 animate={{ strokeDashoffset: 0 }}
                 transition={{ duration: 0.6, ease: "easeOut", delay: 0.3 }}
               />
               <motion.circle 
                 cx="26" cy="26" r="25"
                 initial={{ strokeDasharray: 157, strokeDashoffset: 157 }}
                 animate={{ strokeDashoffset: 0 }}
                 transition={{ duration: 0.8, ease: "easeOut" }}
               />
            </svg>
         </div>
         <motion.div
           initial={{ opacity: 0, y: 10 }}
           animate={{ opacity: 1, y: 0 }}
           transition={{ delay: 0.8 }}
         >
           <h1 className="text-4xl font-display font-bold text-white mb-2">Consultation Complete 🎉</h1>
           <p className="text-white/60">Duration: {durationText} • Dr. Priya Sharma</p>
         </motion.div>
      </div>

      <div className="w-full max-w-3xl grid grid-cols-1 md:grid-cols-12 gap-8">
        
        {/* Left Col: AI Summary */}
        <motion.div 
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 1, duration: 0.5 }}
          className="md:col-span-8 space-y-6"
        >
           {/* Document Card */}
           <div className="bg-[#0A2540] border border-white/10 rounded-3xl p-8 relative overflow-hidden shadow-2xl">
              <div className="absolute top-0 right-0 p-4 opacity-10">
                <FileText className="w-24 h-24" />
              </div>
              
              <div className="flex items-center gap-3 mb-8 pb-6 border-b border-white/10">
                 <div className="w-10 h-10 rounded-full bg-accent/20 flex items-center justify-center">
                    <Stethoscope className="w-5 h-5 text-accent" />
                 </div>
                 <div>
                   <h2 className="text-lg font-bold">Clinical Summary</h2>
                   <p className="text-xs text-white/50">Auto-generated by Sehat AI Assistant</p>
                 </div>
              </div>

              <div className="space-y-6 font-sans">
                 <div>
                    <h3 className="text-sm font-bold text-white/50 uppercase tracking-widest mb-2">Symptoms Discussed</h3>
                    <p className="text-white/80 leading-relaxed text-sm">
                      Patient presented with high fever (102°F) persisting for 48 hours, accompanied by mild headache and body aches. No respiratory distress, cough, or loss of taste/smell reported.
                    </p>
                 </div>

                 <div>
                    <h3 className="text-sm font-bold text-white/50 uppercase tracking-widest mb-2">Doctor's Assessment</h3>
                    <p className="text-white/80 leading-relaxed text-sm">
                      Likely viral etiology (seasonal flu). Vital parameters appear stable based on remote assessment. No red flags for urgent emergency care.
                    </p>
                 </div>

                 {/* Proper Prescription Card */}
                 <div className="bg-white rounded-2xl p-6 text-black relative">
                    <div className="absolute -left-2 top-8 bottom-8 w-4 border-l-4 border-dashed border-[#00C896]/30" />
                    <div className="flex justify-between items-start mb-4 border-b border-black/10 pb-4">
                       <div>
                         <div className="font-bold font-display text-xl text-[#060F1E]">Dr. Priya Sharma</div>
                         <div className="text-xs text-black/60">Reg No: NMC-183049</div>
                       </div>
                       <div className="text-right text-sm font-medium">
                         Rx
                       </div>
                    </div>
                    <div className="space-y-4">
                       <div>
                         <div className="font-bold text-lg flex items-center gap-2">
                           Paracetamol 500mg
                           <span className="text-[10px] bg-blue-100 text-blue-700 px-2 py-0.5 rounded font-bold uppercase tracking-widest">Tablet</span>
                         </div>
                         <div className="text-sm text-black/70 mt-1 flex items-center gap-2">
                           <span>1-1-1</span>
                           <span className="w-1 h-1 rounded-full bg-black/30" />
                           <span>After meals</span>
                           <span className="w-1 h-1 rounded-full bg-black/30" />
                           <span>3 Days</span>
                         </div>
                         <div className="text-xs text-[#EF4444] mt-1 font-medium">Take only if temperature exceeds 100°F (SOS).</div>
                       </div>
                    </div>
                 </div>

                 <div>
                    <h3 className="text-sm font-bold text-white/50 uppercase tracking-widest mb-2">Follow-Up Instructions</h3>
                    <ul className="list-disc list-inside text-white/80 leading-relaxed text-sm space-y-1">
                      <li>Maintain strict hydration (minimum 2.5L water daily).</li>
                      <li>Contact clinic if fever persists beyond 3 days.</li>
                    </ul>
                 </div>
              </div>
           </div>

           {/* Call to Actions */}
           <div className="flex flex-col sm:flex-row gap-4">
              <button 
                onClick={() => setSaved(true)}
                className={cn(
                  "flex-1 py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all",
                  saved 
                    ? "bg-white/10 text-[#00C896] border border-[#00C896]/30 pointer-events-none" 
                    : "bg-[#00C896] text-[#060F1E] hover:scale-[1.02] shadow-[0_10px_20px_rgba(0,200,150,0.2)]"
                )}
              >
                {saved ? <CheckCircle2 className="w-5 h-5" /> : <Save className="w-5 h-5" />}
                {saved ? "Saved to Profile" : "Save to Health Records"}
              </button>
              
              <button className="flex-1 bg-white/5 border border-white/10 text-white py-4 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-white/10 transition-colors">
                <Download className="w-5 h-5" />
                Download Prescription
              </button>
           </div>
        </motion.div>

        {/* Right Col: Rating */}
        <motion.div 
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 1.2, duration: 0.5 }}
          className="md:col-span-4"
        >
           <div className="bg-[#0A2540]/50 border border-white/10 rounded-3xl p-6">
              <h3 className="font-bold mb-1">Rate your experience</h3>
              <p className="text-xs text-white/50 mb-6">Your feedback helps improve our AI and doctors.</p>

              <div className="flex justify-center gap-2 mb-6">
                 {[1, 2, 3, 4, 5].map((star) => (
                   <button
                     key={star}
                     onMouseEnter={() => setHoverRating(star)}
                     onMouseLeave={() => setHoverRating(0)}
                     onClick={() => setRating(star)}
                     className="transition-transform hover:scale-110 focus:outline-none"
                   >
                     <Star 
                       className={cn(
                         "w-8 h-8 transition-colors",
                         (hoverRating || rating) >= star ? "fill-yellow-400 text-yellow-400" : "fill-transparent text-white/20"
                       )} 
                     />
                   </button>
                 ))}
              </div>

              <textarea 
                value={review}
                onChange={(e) => setReview(e.target.value)}
                placeholder="Care to share more about your consultation? (Optional)"
                className="w-full bg-[#060F1E] border border-white/10 rounded-xl p-4 text-sm text-white placeholder-white/30 resize-none h-24 focus:border-accent focus:outline-none transition-colors mb-4 custom-scrollbar"
              />

              <button 
                disabled={rating === 0}
                className="w-full bg-white/10 text-white font-bold py-3 rounded-xl hover:bg-white/20 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                Submit Feedback
                <ChevronRight className="w-4 h-4" />
              </button>
           </div>
        </motion.div>

      </div>
    </div>
  );
}
